name: Deploy incognito docs web page and Publish to PyPI
on:
  push:
    branches:
      - main
  release:
    types:
      - created
permissions:
  contents: write
  packages: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run tests
        run: uv run make test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install python deps
        run: |
          uv add mkdocs mkdocstrings-python
      - name: Build doc
        run: |
          uv run python -m mkdocs build -f ./docs/mkdocs.yml -d www
      - name: Check files
        run: |
          ls docs/www
      - name: Deploy page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/www
          token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build package
        run: uv build
      - name: Publish package to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv publish --token $PYPI_API_TOKEN
  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get version from pyproject.toml
        id: get_version
        run: echo "VERSION=$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)" >> $GITHUB_ENV
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: "New release of the package."
          draft: false
          prerelease: false
          files: |
            dist/*
